### ISSUE TITLE
[BUG] The aspect ratio of video is wrong

### ISSUE THREAD

**Issue by kwarnkham** [fluttercandies/flutter_wechat_camera_picker#272]
**Describe the bug**
The aspect ratio of video is wrong. I took the video by long press the button in portrait orientation. But in preview and saved file, the orientation or aspect ratio is changed to landscape.

**How to reproduce**
```
final AssetEntity? entity = await CameraPicker.pickFromCamera(
            context,
            pickerConfig: const CameraPickerConfig(
              enableRecording: true,
            ),
          );
```

**Expected behavior**
The preview should be the same as the view while recording the video.

**Screenshots (If contains)**
![photo_2024-09-05 13 34 58](https://github.com/user-attachments/assets/49007043-04b0-4bd3-b419-900cd5392fb2)
![photo_2024-09-05 13 35 01](https://github.com/user-attachments/assets/9e87e14c-826b-44a4-af55-9887c1830d44)

**Version information**

- Device: Samsung Galaxy S22 Ultra
- OS: Android 14, One UI 6.1
- Package Version: 4.3.2
sdks:
  dart: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

**Comment by AlexV525** [comment]
This may already fixed by `photo_manager: ^3.3.0`, could you confirm that?

**Comment by kwarnkham** [comment]
```
photo_manager:
    dependency: transitive
    description:
      name: photo_manager
      sha256:
      url: "https://pub.dev"
    source: hosted
    version: "3.3.0"
 ```
 
 I found this in my pubspec.lock.
 
 Probably not fixed.
